export default function Budget() {
  return (
    <>
      <div>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
        <p>Budget</p>
      </div>
    </>
  );
}
