export default function TravelPlan(): JSX.Element {
  return (
    <>
      <div className="bg-teal-500 ">
        <div>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
          <p>TravelPlan</p>
        </div>
      </div>
    </>
  );
}
